# These are supported funding model platforms
custom: https://sociabuzz.com/zuax/tribe
<<<<<<< HEAD
ko_fi: https://ko-fi.com/mahiro885
=======
ko_fi: https://ko-fi.com/mahiro885
>>>>>>> 4981c5fb203dfe9acdce0c281f01abef327065ab
